version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=noon
    volumes:
      - ./../volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    ports:
      - '4873:4873'

