version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=noon
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=kozbara
    volumes:
      - ./../volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    ports:
      - '4873:4873'

  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    volumes:
      - ./../volumes/neo4j/data:/data
      - ./../volumes/neo4j/logs:/logs
      - ./../volumes/neo4j/import:/var/lib/neo4j/import
      - ./../volumes/neo4j/plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    volumes:
      - ./../volumes/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - esnet
networks:
  esnet:
